# Generated by Django 4.2.3 on 2023-07-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Book Title')),
                ('author', models.CharField(max_length=100, verbose_name='Author')),
                ('year', models.IntegerField(verbose_name='Year Published')),
            ],
        ),
    ]
